from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, ConfigDict, Field
from app.schemas.decision import RecoveryAction

class GuardrailStatus(str, Enum):
    ALLOW = "ALLOW"
    MODIFY = "MODIFY"
    BLOCK = "BLOCK"

class GuardrailRuleEvaluation(BaseModel):
    rule_id: str
    rule_name: str
    status: GuardrailStatus
    severity: str = "LOW"  # LOW, MEDIUM, HIGH, CRITICAL
    message: str
    model_config = ConfigDict(from_attributes=True)

class GuardrailResult(BaseModel):
    """
    Deterministic Safety Result generated by Independent Guardrail Engine.
    Exposes ALLOW, MODIFY, or BLOCK status and final action authority.
    """
    payment_id: str
    original_action: RecoveryAction
    final_action: RecoveryAction
    status: GuardrailStatus
    rules_evaluated: List[str]
    rules_triggered: List[str]
    reason: str
    risk_level: str = "LOW"
    requires_human_review: bool = False
    rule_details: List[GuardrailRuleEvaluation] = Field(default_factory=list)
    
    model_config = ConfigDict(from_attributes=True)

class GuardrailEvaluationRequest(BaseModel):
    payment_id: Optional[str] = None
    proposed_action: Optional[RecoveryAction] = None
    # Optional ad-hoc override features if testing uncommitted payments
    amount: Optional[float] = None
    payment_method: Optional[str] = None
    failure_reason: Optional[str] = None
